language: cpp

branches:
  only:
  - testci

before_install:
  - pip install alibuild && aliBuild analytics off

install:

script:
  - aliBuild --defaults alo build ROOT

after_script:
  - ls $HOME

cache:
  directories:
  - $HOME/sw/TARS
