language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

branches:
  only:
  - testci

before_install:
  - eval "${MATRIX_EVAL}"
  - ${CXX} --version
  - pip install alibuild
  - aliBuild analytics off
  - cd $HOME && git clone https://github.com/alisw/alidist.git
  - printenv
  - aliDoctor ROOT

script:
  - aliDoctor alo

after_script:
  - ls -alR $HOME

