language: cpp

branches:
  only:
  - testci

before_install:
  - pip install alibuild
  - aliBuild analytics off
  - git clone https://github.com/alisw/alidist.git

install:

script:
  - aliBuild --defaults alo build ROOT

after_script:
  - ls -alR $HOME

cache:
  directories:
  - $HOME/sw/TARS
