sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libperl-dev
      - python-dev
      - environment-modules 
      - pkg-config 
      - build-essential 
      - autoconf 
      - automake 
      - autopoint
      - texinfo
      - gettext
      - libtool
      - swig
      - tree

branches:
  only:
  - testci

before_install:
  - echo "export PATH=$HOME:$PATH" >> $HOME/.bashrc
  - cd $HOME/bin
  - ln -si /usr/bin/gcc-5 cc
  - ln -si /usr/bin/g++-5 c++
  - ln -si /usr/bin/gfortran-5 gfortran
  - pip install alibuild
  - aliBuild analytics off
  - cd $HOME/build 
  - git clone https://github.com/alisw/alidist.git

script:
  - cd $HOME
  - which cc
  - echo $PATH | tr ":" "\n"
  - cd $HOME/build
  - aliDoctor alo
  - aliBuild --defaults alo build alo

after_script:
  - tree $HOME -L 3
