sudo: false

language: cpp

perl:
  - "5.24"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libtool 
      - pkg-config 
      - build-essential 
      - autoconf 
      - automake 
      - uuid-dev

branches:
  only:
  - testci

before_install:
  - export CC=gcc-5 
  - export CXX=g++-5
  - ${CXX} --version
  - pip install alibuild
  - aliBuild analytics off
  - echo $HOME
  - cd $HOME && git clone https://github.com/alisw/alidist.git
  - printenv

script:
  - aliDoctor alo

after_script:
  - ls -alR $HOME

