language: cpp

branches:
  only:
  - testci

before_install:
  - pip install alibuild
  - aliBuild analytics off
  - git clone https://github.com/alisw/alidist.git

script:
  - aliDoctor ROOT

after_script:
  - ls -alR $HOME

