sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - libperl-dev
      - python-dev
      - environment-modules 
      - pkg-config 
      - build-essential 
      - autoconf 
      - automake 
      - autopoint
      - texinfo
      - gettext
      - libtool
      - swig
      - tree

branches:
  only:
  - testci

before_install:
  - echo "export PATH=$HOME/bin:$PATH" >> $HOME/.bashrc
  - echo "export CC=/usr/bin/gcc-6" >> $HOME/.bashrc
  - echo "export CXX=/usr/bin/g++-6" >> $HOME/.bashrc
  - cd $HOME/bin
  - ln -si /usr/bin/gcc-6 cc
  - ln -si /usr/bin/gcc-6 gcc
  - ln -si /usr/bin/g++-6 c++
  - ln -si /usr/bin/g++-6 g++
  - ln -si /usr/bin/gfortran-6 gfortran
  - pip install alibuild
  - aliBuild analytics off
  - mkdir -p $HOME/build/aphecetche 
  - cd $HOME/build/aphecetche 
  - git clone https://github.com/alisw/alidist.git

script:
  - cd $HOME/build/aphecetche 
  - export PATH=$HOME/bin:$PATH
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - rm -rf $HOME/build/aphecetche/sw/BUILD/CMake*
  - aliBuild --defaults alo build alo

after_script:
  - cat $HOME/build/aphecetche/sw/BUILD/CMake-latest/log
